---
project: deblur_gan
experiment_desc: fpn

train:
  files_a: &FILES_A /home/deng426/tangkang/DeblurGANv2-master/datasets/GOPRO/GOPRO_3840FPS_AVG_3-21/train/blur/*/*.png
  files_b: &FILES_B /home/deng426/tangkang/DeblurGANv2-master/datasets/GOPRO/GOPRO_3840FPS_AVG_3-21/train/sharp/*/*.png
  size: &SIZE 720
  crop: random
  preload: &PRELOAD false
  preload_size: &PRELOAD_SIZE 0
  bounds: [0, .9]
  scope: geometric
  corrupt: &CORRUPT
    - name: cutout
      prob: 0.5
      num_holes: 3
      max_h_size: 25
      max_w_size: 25
    - name: jpeg
      quality_lower: 70
      quality_upper: 90
    - name: motion_blur
    - name: median_blur
    - name: gamma
    - name: rgb_shift
    - name: hsv_shift
    - name: sharpen

val:
  files_a: &FILES_C /home/deng426/tangkang/DeblurGANv2-master/datasets/GOPRO/GOPRO_3840FPS_AVG_3-21/test/blur/*/*.png
  files_b: &FILES_D /home/deng426/tangkang/DeblurGANv2-master/datasets/GOPRO/GOPRO_3840FPS_AVG_3-21/test/sharp/*/*.png
  size: *SIZE
  scope: geometric
  crop: center
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  bounds: [.9, 1]
  corrupt: *CORRUPT

phase: train
warmup_num: 3
model:
  g_name: fpn_inception
  blocks: 9
  d_name: double_gan # may be no_gan, patch_gan, double_gan, multi_scale
  d_layers: 3
  content_loss: perceptual
  adv_lambda: 0.001
  disc_loss: ragan-ls
  learn_residual: True
  norm_layer: instance
  dropout: True

num_epochs: 1500
train_batches_per_epoch: 1000
val_batches_per_epoch: 100
batch_size: 1
image_size: [720,1280]

optimizer:
  name: adam
  lr: 0.0001
scheduler:
  name: linear
  start_epoch: 150
  min_lr: 0.0000001

